# Generated by Django 5.0.1 on 2024-01-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
